# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopPick' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopPick

  target 'PopPickTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PopProduct' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopProduct

  target 'PopProductTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PopProductUITests' do
    # Pods for testing
  end

end
